'use client';

import { ChakraProvider } from '@chakra-ui/react';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const theme = {
	fonts: {
		heading: '"Avenir Next", sans-serif',
		body: '"Open Sans", sans-serif',
	},
	colors: {
		brand: {
			bg: '#9747FF',
			text: '#fff',
			card: '#0A99FF',
		},
	},
	sizes: {
		xl: {
			h: '56px',
			fontSize: 'lg',
			px: '32px',
			bg: '#9747FF',
		},
	},
};

const theme = extendTheme({
	colors: {
		blue: {
			500: '#007bff',
		},
	},
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable}`}>
				<ChakraProvider theme={theme}>{children}</ChakraProvider>
			</body>
		</html>
	);
}
